var accounts =[
{
"accountid": "0123",
"email": "mark@gmail.com",
"password": "mark123",
"lastname": "Quijom",
"firstname": "Mark Jhon Paul",
"middlename": "Garcia",
"suffix": "-",
"birthdate": "1995-05-25",
"birthplace": "Kalookan City",
"nickname": "Mark, Mjp",
"gender": "Male",
"contact": "09463773777",
"civilstatus": "Single",
"citizenship": "Filipino",
"spousename": "-",
"spousebplace": "-",
"address": "Blk3 Lot7 Sta Isabel St. Gulod Novaliches Quezon City",
"fathername": "Jesus R. Quijom",
"fatherbplace": "Vigan, Ilocos Sur",
"mothername": "Madeline G. Quijom",
"motherbplace": "Bulag Centro, Ilocos Sur",
"educattain": "COLLEGE GRADUATE",
"occupation": "Jr. Java Developer",
"religion": "Roman Catholic",
"userheight": "55",
"userweight": "50",
"idmarks": "-",
"datecreated": "September 22, 2016",
"transactionno": "AOXQ6290",
"transactiondate": "Thu Sep 01 2016",
"transactionstatus": "PAID"
}
];
